server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://liuxl1:8180/eureka/,http://liuxl:8080/eureka/,http://liuxl2:8280/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo