eureka:
  client:
    serviceUrl:
      defaultZone: http://liuxl1:8180/eureka/,http://liuxl:8080/eureka/,http://liuxl2:8280/eureka/
server:
  port: 8081
spring:
  application:
    name: member
#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springCould?useUnicode=true&characterEncoding=utf8
  username: root
  password: ypm2al

#mybatis config
mybatis:
  typeAliasesPackage: com.bs.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2.xml