eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@server1:8180/eureka/,http://admin:admin@server:8080/eureka/,http://admin:admin@server2:8280/eureka/
server:
  port: 8083
spring:
  application:
    name: web
#打开断路器
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: member
logging:
  config: classpath:log4j2.xml
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign

#spring.beetl.root = classpath:/templates/
#spring.beetl.prefix =
#spring.beetl.suffix = .html
#spring.beetl.order = 0
#spring.beetl.cofig = classpath:beetl.properties
