eureka:
  client:
    serviceUrl:
      defaultZone: http://liuxl1:8180/eureka/,http://liuxl:8080/eureka/,http://liuxl2:8280/eureka/
server:
  port: 8083
spring:
  application:
    name: web
#打开断路器
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: member
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign