server:
  port: 8180
eureka:
#  server:
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 4000
  instance:
    hostname: liuxl1
    instance-id: ${spring.application.name}:${server.port}
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://liuxl:8080/eureka/,http://liuxl2:8280/eureka/