server:
  port: 8280
eureka:
#  server:
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 4000
  instance:
    hostname: server2
    instance-id: ${spring.application.name}:${server.port}
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@server1:8180/eureka/,http://admin:admin@server:8080/eureka/